#!/bin/bash


AUTO_SETUP_PY_FILE="${PWD}/load_post_run.py"

AUTO_KICKOFF_FILE="${PWD}/ZNY_ATCKLST_M.py"

echo -e "Pushing files ${AUTO_SETUP_PY_FILE} and ${AUTO_KICKOFF_FILE} to the ZOA and ZNY ATChecklist DIST and SCRIPTS folders. . . .\n"

#echo $PWD
#ATC Test folders
scp $AUTO_SETUP_PY_FILE /home/users/gbg/${USER}/ATChecklist/ZOA/DIST
scp $AUTO_KICKOFF_FILE /home/users/gbg/${USER}/ATChecklist/ZOA/SCRIPTS
scp $AUTO_SETUP_PY_FILE /home/users/gbg/${USER}/ATChecklist/ZNY/DIST
scp $AUTO_KICKOFF_FILE /home/users/gbg/${USER}/ATChecklist/ZNY/SCRIPTS

#DIL Test folders
scp $AUTO_SETUP_PY_FILE /home/users/gbg/${USER}/ZOA_DIL/DIST
scp $AUTO_KICKOFF_FILE /home/users/gbg/${USER}/ZOA_DIL/SCRIPTS
scp $AUTO_SETUP_PY_FILE /home/users/gbg/${USER}/ZNY_DIL/DIST
scp $AUTO_KICKOFF_FILE /home/users/gbg/${USER}/ZNY_DIL/SCRIPTS

echo -e "DONE....\n"

exit
